dist: trusty
sudo: required

language:
  c++

os:
  - osx
  # Ignore linux now, will be supported later
  # - linux

compiler:
  - clang
  - gcc

env:
  - MODE="debug"

matrix:
  exclude:
    - os: osx
      compiler: gcc

    - os: linux
      compiler: clang

script:
  - mkdir build
  - cd build
  - cmake .. -DMODE=$MODE
  - make
  - ./Tests/Core/BerserkTestsCore