dist: trusty
sudo: required

language:
  c++

os:
  - osx
  - linux

compiler:
  - clang
  - gcc

env:
  - CMODE_DEBUG=ON CMODE_RELEASE=OFF CPLATFORM_MAC=ON CPLATFORM_LINUX=OFF
  - CMODE_DEBUG=ON CMODE_RELEASE=OFF CPLATFORM_LINUX=ON CPLATFORM_MAC=OFF

matrix:
  exclude:
    - os: osx
      compiler: gcc

    - os: linux
      compiler: clang

    - os: osx
      env: CMODE_DEBUG=ON CMODE_RELEASE=OFF CPLATFORM_LINUX=ON CPLATFORM_MAC=OFF

    - os: linux
      env: CMODE_DEBUG=ON CMODE_RELEASE=OFF CPLATFORM_MAC=ON CPLATFORM_LINUX=OFF

script:
  - mkdir build
  - cd build
  - cmake .. -DCMODE_DEBUG=$MODE_DEBUG -DCMODE_RELEASE=$MODE_RELEASE -DCPLATFORM_MAC=$CPLATFORM_MAC -DCPLATFORM_LINUX=$CPLATFORM_LINUX
  - make
  - ./Tests/BerserkTests