sudo: required

language: c++

os:
  - osx

compiler:
  - clang

env:
  - MODE_DEBUG=ON MODE_RELEASE=OFF

build_script:
  - mkdir build
  - cd build
  - cmake .. -DMODE_DEBUG=$MODE_DEBUG -DMODE_RELEASE=$MODE_RELEASE
  - make

test_script:
  - ./Tests/BerserkTests