sudo: required

language: c++

os:
  - osx

compiler:
  - clang

env:
  - CMODE_DEBUG=ON CMODE_RELEASE=OFF CPLATFORM_MAC=ON

script:
  - mkdir build
  - cd build
  - cmake .. -DCMODE_DEBUG=$MODE_DEBUG -DCMODE_RELEASE=$MODE_RELEASE -DCPLATFORM_MAC=$CPLATFORM_MAC
  - make

test_script:
  - ./Tests/BerserkTests