dist: trusty
sudo: required

language:
  c++

os:
  - osx
  # Ignore linux now, will be supported later
  # - linux

compiler:
  - clang
  - gcc

env:
  - MODE="debug" PLATFORM="mac"
  - MODE="debug" PLATFORM="linux"

matrix:
  exclude:
    - os: osx
      compiler: gcc

    - os: linux
      compiler: clang

    - os: osx
      env: MODE="debug" PLATFORM="linux"

    - os: linux
      env: MODE="debug" PLATFORM="mac"

script:
  - mkdir build
  - cd build
  - cmake .. -DMODE=$MODE -DPLATFORM=$PLATFORM
  - make
  - ./Tests/BerserkTests