//
// Created by Egor Orachyov on 04.07.2018.
//

#ifndef BERSERKENGINE_GLVERTEXARRAYOBJECT_H
#define BERSERKENGINE_GLVERTEXARRAYOBJECT_H


class GLVertexArrayObject {

};


#endif //BERSERKENGINE_GLVERTEXARRAYOBJECT_H
