//
// Created by Egor Orachyov on 22.03.2019.
//

#ifndef BERSERK_PROFILINGMACRO_H
#define BERSERK_PROFILINGMACRO_H

#ifndef PROFILE_POOL_ALLOCATOR
    #define PROFILE_POOL_ALLOCATOR 0
#endif // PROFILE_POOL_ALLOCATOR

#ifndef PROFILE_LINKED_LIST
    #define PROFILE_LINKED_LIST 0
#endif // PROFILE_LINKED_LIST

#ifndef PROFILE_ARRAY_LIST
    #define PROFILE_ARRAY_LIST 0
#endif // PROFILE_ARRAY_LIST

#ifndef PROFILE_HASH_MAP
    #define PROFILE_HASH_MAP 0
#endif // PROFILE_HASH_MAP

#endif //BERSERK_PROFILINGMACRO_H
