name: MacOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build Engine Sources
    runs-on: macos-latest
    env:
      build_dir: "build"
      config: "Release"
      artifact: "macos-build.tar.xz"

    steps:
    - uses: actions/checkout@v2

    - name: Install vulkan sdk
      shell: bash
      run: |
        mkdir vulkan
        cd vulkan
        curl "https://sdk.lunarg.com/sdk/download/1.2.176.1/mac/vulkansdk-macos-1.2.176.1.dmg?Human=true" --output vulkansdk-macos-1.2.176.1.dmg
        sudo hdiutil attach vulkansdk-macos-1.2.176.1.dmg
        cd /Volumes/vulkansdk-macos-1.2.176.1
        sudo ./InstallVulkan.app/Contents/MacOS/InstallVulkan --root ~/VulkanSDK/1.2.176.1 --accept-licenses --default-answer --confirm-command install

    - name: Configure CMake
      shell: bash
      run: cmake . -B ${{env.build_dir}} -DCMAKE_BUILD_TYPE=${{env.config}}
    
    - name: Build engine source
      working-directory: ${{env.build_dir}}
      shell: bash
      run: cmake --build . --verbose -j `nproc`

    - name: Run core tests
      working-directory: ${{env.build_dir}}
      shell: bash
      run: bash Scripts/run_tests.sh

    - name: Prepare upload binary
      shell: bash
      run: tar cfz ${{env.artifact}} ${{env.build_dir}}

    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: ${{env.artifact}}
        path: ${{env.artifact}}
