name: pages

on:
  push:
    branches: [ master ]
    paths:
      - '.github/**'
      - 'code/**'
      - 'Doxyfile'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate documentation
        uses: mattnotmitt/doxygen-action@v1.3.1

      - name: Publish to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html/