name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build Berserk Engine
    runs-on: ubuntu-latest
    env:
      build_dir: "build"
      config: "Release"

    steps:
    - uses: actions/checkout@v2
    
    - name: Install build requirements
      shell: bash
      run: |
        sudo apt-get update -y
        sudo apt-get install -y build-essential
        sudo apt-get install -y cmake
        
    - name: Install glfw dependencies
      shell: bash
      run: |
        sudo apt-get install -y libxrandr-dev libxinerama-dev xorg-dev

    - name: Install glew dependencies
      shell: bash
      run: |
        sudo apt-get install -y libgl1-mesa-dri libgl1-mesa-glx libgl1-mesa-dev
        sudo apt-get install -y libxmu-dev libxi-dev libgl-dev libglx-dev
        sudo apt-get install -y libx11-dev

    - name: Configure CMake
      shell: bash
      run: cmake . -B ${{env.build_dir}} -DCMAKE_BUILD_TYPE=${{env.config}}
    
    - name: Build engine source
      working-directory: ${{env.build_dir}}
      shell: bash
      run: cmake --build . --verbose -j `nproc`

    - name: Run core tests
      working-directory: ${{env.build_dir}}
      shell: bash
      run: bash Scripts/run_tests.sh
      
