name: Windows

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'Docs/**'
      - 'Engine/**'
      - 'Ide/**'
      - 'Scripts/**'
      - .gitignore
      - AUTHORS.md
      - CHANGELOG.md
      - CODE_OF_CONDUCT.md
      - DEPENDENCIES.md
      - LICENSE.md
      - README.md
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build Berserk Engine
    runs-on: windows-latest
    env:
      build_dir: "build"
      config: "Release"
      artifact: "berserk-windows-build.tar.xz"
      nproc: "4"

    steps:
      - uses: actions/checkout@v2

      - name: Install vulkan sdk
        shell: cmd
        run: |
          curl -L --output VulkanSDK.exe https://sdk.lunarg.com/sdk/download/1.2.182.0/windows/VulkanSDK-1.2.182.0-Installer.exe?Human=true
          VulkanSDK.exe /S

      - name: Setup Env
        shell: bash
        run: echo "VULKAN_SDK=C:/VulkanSDK/1.2.182.0" >> $GITHUB_ENV

      - name: Configure CMake
        shell: bash
        run: cmake . -B ${{env.build_dir}} -DCMAKE_BUILD_TYPE=${{env.config}}

      - name: Build engine source
        working-directory: ${{env.build_dir}}
        shell: bash
        run: cmake --build . --verbose -j ${{env.nproc}}

      - name: Run core tests
        working-directory: ${{env.build_dir}}
        shell: bash
        run: bash Scripts/run_tests.sh

      - name: Prepare upload binary
        shell: bash
        run: tar cfz ${{env.artifact}} ${{env.build_dir}}

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.artifact}}
          path: ${{env.artifact}}
