//
// Created by Egor Orachyov on 25.05.2018.
//

#ifndef BERSERKENGINE_DOUBLEFRAMEMANAGER_H
#define BERSERKENGINE_DOUBLEFRAMEMANAGER_H


class DoubleFrameManager {

};


#endif //BERSERKENGINE_DOUBLEFRAMEMANAGER_H
